### ISSUE TITLE
Homebridge crashes when API fails

### ISSUE THREAD

**Issue by rafacampoamor** [nitaybz/homebridge-tado-ac-old#18]
I’m getting crashes after the Tado API fails. Here is the error I’m getting:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

```

**Comment by nitaybz** [comment]
I'm experiencing the same issues every once an a while but I don't know how to solve it...
any help would be much appreciated !

**Comment by nitaybz** [comment]
Closing this. This repository is the old/superseded version of the tado AC plugin and is no longer maintained. The newer repo (homebridge-tado-ac) has also just been deprecated because tado deprecated their authentication API in March 2025.

Please migrate to @homebridge-plugins/homebridge-tado v8+ which is actively maintained and supports tado AC: https://www.npmjs.com/package/@homebridge-plugins/homebridge-tado

Sorry for the long delay on this one.
